Repository AUCyberClub/axion, pull requests merged in 2018-03, with the labels that each got.

#1 RAM Dump options Added
  Axion.py
  imports/volatility_cmdscan.py
  imports/volatility_iehistory.py
  imports/volatility_info.py
  imports/volatility_notepad.py
  imports/volatility_pslist.py
  imports/volatility_screenshot.py
Labels: enhancement

#2 Path completion with tab key added
  Axion.py
  README.md
Labels: enhancement, feature

#3 Basic localization
  axion.py
  locale/en/LC_MESSAGES/axion.mo
  locale/en/LC_MESSAGES/axion.po
  locale/tr/LC_MESSAGES/axion.mo
  locale/tr/LC_MESSAGES/axion.po
Labels: translate

#4 New crypto modules
  axion.py
  imports/base64_decoder.py
  imports/xor_decoder.py
  requirements.txt
Labels: enhancement

#7 New crypto modules
  axion.py
  imports/bin_hex_dec_ascii.py
  imports/rot13_caesar.py
Labels: enhancement

#8 other_tool
  axion.py
  imports/pdf_parser.py
Labels: enhancement, feature

#10 Code optimizations
  axion.py
  imports/base64_decoder.py
  imports/bin_hex_dec_ascii.py
  imports/binary_search.py
  imports/find_file_ext.py
  imports/hash_brute.py
  imports/hash_extractor.py
  imports/hash_ident.py
  imports/metadata_search.py
  imports/morse_decoder.py
  imports/morse_encoder.py
  imports/pdf_parser.py
  imports/rot13_caesar.py
  imports/vigenere_decoder.py
  imports/volatility_cmdscan.py
  imports/volatility_iehistory.py
  imports/volatility_info.py
  imports/volatility_notepad.py
  imports/volatility_pslist.py
  imports/volatility_screenshot.py
  imports/xor_decoder.py
  requirements.txt
Labels: enhancement

#12 Localization
  axion.py
  imports/base64_decoder.py
  imports/bin_hex_dec_ascii.py
  imports/binary_search.py
  imports/find_file_ext.py
  imports/hash_brute.py
  imports/hash_extractor.py
  imports/hash_ident.py
  imports/metadata_search.py
  imports/morse_decoder.py
  imports/morse_encoder.py
  imports/pdf_parser.py
  imports/rot13_caesar.py
  imports/vigenere_decoder.py
  imports/volatility_cmdscan.py
  imports/volatility_iehistory.py
  imports/volatility_info.py
  imports/volatility_notepad.py
  imports/volatility_pslist.py
  imports/volatility_screenshot.py
  imports/xor_decoder.py
  locale/en/LC_MESSAGES/axion.mo
  locale/en/LC_MESSAGES/axion.po
  locale/tr/LC_MESSAGES/axion.mo
  locale/tr/LC_MESSAGES/axion.po
Labels: enhancement, translate

#13 Update readme.md
  README.md
  screenshots/1-2.png
  screenshots/2.png
  screenshots/3.png
  screenshots/a1.png
  screenshots/a2.png
  screenshots/a3.png
  screenshots/axionLogo.jpg
Labels: enhancement

#15 Semarnek patch 1
  Installiation.sh
  README.md
Labels: enhancement

#17 Semarnek patch 1
  imports/morse_encoder.py
  imports/rot13_caesar.py
  screenshots/OS.png
  screenshots/binwalk.png
  screenshots/caesar.png
  screenshots/exiftool.png
  screenshots/file_menu.png
  screenshots/find_file.png
  screenshots/hash_ident.png
  screenshots/morse_decoder.png
  screenshots/morse_encoder.png
  screenshots/ps_list.png
  screenshots/vigenere.png
Labels: bug, enhancement
