Repository AUCyberClub/axion, pull requests merged in 2018-04, with the labels that each got.

#18 Update Installiation.sh
  Installiation.sh
Labels: enhancement

#20 Add Reverse Handbook
  axion.py
  handbook_files/reverse/images/rev1.png
  handbook_files/reverse/images/rev2.png
  handbook_files/reverse/images/rev3.png
  handbook_files/reverse/images/rev4.png
  handbook_files/reverse/images/rev5.png
  handbook_files/reverse/images/rev6.png
  handbook_files/reverse/images/rev7.png
  handbook_files/reverse/images/rev8.png
  handbook_files/reverse/reverse.md
  imports/handbook.py
  imports/pdf_parser.py
  requirements.txt
Labels: feature

#21 Handbook
  handbook_files/crypto/crypto.md
  handbook_files/crypto/images/cry1.png
  handbook_files/crypto/images/cry2.png
  handbook_files/crypto/images/cry3.png
  handbook_files/crypto/images/cry4.png
  handbook_files/crypto/images/cry5.png
  handbook_files/crypto/images/cry6.png
  handbook_files/crypto/images/cry7.png
  imports/base64_decoder.py
  imports/bin_hex_dec_ascii.py
  imports/binary_search.py
  imports/find_file_ext.py
  imports/handbook.py
  imports/hash_brute.py
  imports/hash_extractor.py
  imports/hash_ident.py
  imports/metadata_search.py
  imports/morse_decoder.py
  imports/morse_encoder.py
  imports/pdf_parser.py
  imports/rot13_caesar.py
  imports/vigenere_decoder.py
  imports/xor_decoder.py
Labels: feature

#22 Fixed some volatility bugs and some new improvements
  imports/volatility_cmdscan.py
  imports/volatility_iehistory.py
  imports/volatility_info.py
  imports/volatility_notepad.py
  imports/volatility_pslist.py
  imports/volatility_screenshot.py
Labels: bug, enhancement
