Repository AUCyberClub/axion, pull requests merged in 2018-05, with the labels that each got.

#24 handbook module restructured
  handbook_files/crypto/crypto.html
  handbook_files/crypto/crypto.md
  handbook_files/crypto/crypto_files/cry1.png
  handbook_files/crypto/crypto_files/cry2.png
  handbook_files/crypto/crypto_files/cry3.png
  handbook_files/crypto/crypto_files/cry4.png
  handbook_files/crypto/crypto_files/cry5.png
  handbook_files/crypto/crypto_files/cry6.png
  handbook_files/crypto/crypto_files/cry7.png
  handbook_files/reverse/images/rev8.png
  handbook_files/reverse/reverse.html
  handbook_files/reverse/reverse.md
  handbook_files/reverse/reverse_files/rev1.png
  handbook_files/reverse/reverse_files/rev2.png
  handbook_files/reverse/reverse_files/rev3.png
  handbook_files/reverse/reverse_files/rev4.png
  handbook_files/reverse/reverse_files/rev5.png
  handbook_files/reverse/reverse_files/rev6.png
  handbook_files/reverse/reverse_files/rev8.png
  imports/handbook.py
  requirements.txt
Labels: enhancement, feature

#28 John fix
  Installiation.sh
  imports/globals.ini
  imports/hash_brute.py
  imports/pdf_parser.py
Labels: bug, enhancement

#29 Fixed hash modules and pdf parser
  Installiation.sh
  imports/globals.ini
  imports/hash_brute.py
  imports/hash_extractor.py
  imports/pdf-parser.py
  imports/pdf_parser.py
Labels: bug, enhancement, feature

#31 Some little RAM Dump module fixes
  imports/globals.ini
  imports/volatility_cmdscan.py
  imports/volatility_iehistory.py
  imports/volatility_info.py
  imports/volatility_notepad.py
  imports/volatility_pslist.py
  imports/volatility_screenshot.py
Labels: bug

#32 QRCode module added
  Installiation.sh
  axion.py
  imports/qr_decoder.py
Labels: feature
